### ISSUE TITLE
Error after executing the subtraction code

### ISSUE THREAD

**Issue by astrohitc** [GOTO-OBS/ZiP#10]
Hi,

I tried running the code given in the repository

`ZOGY file.fits ref-file.fits` 

I am getting the following error:

`Traceback (most recent call last):
  File "/home/rohit/miniconda3/lib/python3.9/site-packages/zogyp/spali2.py", line 20, in <module>
    subprocess.call(sex, stderr=subprocess.DEVNULL)
  File "/home/rohit/miniconda3/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/rohit/miniconda3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/rohit/miniconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sextractor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohit/miniconda3/bin/ZOGY", line 5, in <module>
    from zogyp.ZOGY import main
  File "/home/rohit/miniconda3/lib/python3.9/site-packages/zogyp/ZOGY.py", line 17, in <module>
    from zogyp.zip import run_ZOGY
  File "/home/rohit/miniconda3/lib/python3.9/site-packages/zogyp/zip.py", line 37, in <module>
    from zogyp.spali2 import spalipy
  File "/home/rohit/miniconda3/lib/python3.9/site-packages/zogyp/spali2.py", line 23, in <module>
    subprocess.call(sex, stderr=subprocess.DEVNULL) 
  File "/home/rohit/miniconda3/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/rohit/miniconda3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/rohit/miniconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sex'
`

Could you please help me with this?

**Comment by spyphyz** [comment]
It could be an issue with not having SEx/Sextractor/Source-Extractor installed. 
You've got some options:
1. conda install astromatic-source-extractor, in your ZogyP environment
2. brew install sextractor

I'm sure there are other ways too. 

You may have to play about with execution paths if you do it the homebrew way. Basically at the end of the day you want to be able to type into your Terminal sex or source-extractor and get a brief return that looks like this:

**SExtractor  version 2.28.0 (2023-03-11)

**Written by Emmanuel BERTIN <bertin@iap.fr>
Copyright 2012-2015 IAP/CNRS/UPMC

visit http://astromatic.net/software/sextractor

SExtractor comes with ABSOLUTELY NO WARRANTY
You may redistribute copies of SExtractor
under the terms of the GNU General Public License.

> SYNTAX: sex <image> [<image2>][-c <configuration_file>][-<keyword> <value>]
> to dump a default configuration file:          sex -d 
> to dump a default extended configuration file: sex -dd 
> to dump a full list of measurement parameters: sex -dp**** 


If this is all on completely the wrong track and you've tried this already, I apologise.

Bw, Simon
